### PR TITLE
Fix: Semaphore.lock waits to yield

### LINKED ISSUE #37: Semaphore.lock yields even if lock not obtained
If the [lock](https://github.com/rapid7/daemon_runner/blob/master/lib/daemon_runner/semaphore.rb#L20) is not obtained sucessfully the first time, [renew](https://github.com/rapid7/daemon_runner/blob/master/lib/daemon_runner/semaphore.rb#L23) will not help to try again because it is acting on changes on other `sesson.id`s.

Solving #26 might help solve this, we could add a check to ensure the lock was obtained before calling `yield`.

cc: @fmitchell-r7

### PR DESCRIPTION
**Pull request by fmitchell-r7**
This fixes #37. Calls to `Semaphore.lock` that are passed a block will now wait until the lock is acquired before yielding to the block.

### CODE REVIEW

File: lib/daemon_runner/semaphore.rb [hunk 1]
```diff
@@ -22,6 +22,7 @@ def lock(name, limit = 3, **options)
         if block_given?
           begin
             lock_thr = semaphore.renew
+            loop until semaphore.locked?
```
Comment (athompson-r7) [inline lib/daemon_runner/semaphore.rb]: I think this should be above `semaphore.renew` and if `locked?` is `false` you need to call `try_lock` to try to obtain the lock again.

**Review by athompson-r7 — CHANGES_REQUESTED** [review]

**Review by athompson-r7 — APPROVED** [review]
