### PR TITLE
Fix Semaphore.lock fails without block

### LINKED ISSUE #35: Semaphore.lock fails if a block's not given
If [Semaphore.lock](https://github.com/rapid7/daemon_runner/blob/0.4.1/lib/daemon_runner/semaphore.rb#L17-L34) is never given a block, it won't create a new thread to renew the lock. This makes [the call to `lock_thr.kill`](https://github.com/rapid7/daemon_runner/blob/0.4.1/lib/daemon_runner/semaphore.rb#L31) fail with a `NoMethodError`.

Running `rake test` on v0.4.1 gives me this error
```
SemaphoreTest#test_can_get_two_uniq_lock_sessions:
NoMethodError: undefined method `kill' for nil:NilClass
    lib/daemon_runner/semaphore.rb:31:in `lock'
    test/daemon_runner/semaphore_test.rb:114:in `test_can_get_two_uniq_lock_sessions'
```

### PR DESCRIPTION
**Pull request by fmitchell-r7**
This fixes #35. We no longer try to kill the renewal thread if it hasn't been spawned.

### CODE REVIEW

File: lib/daemon_runner/semaphore.rb [hunk 1]
```diff
@@ -28,7 +28,7 @@ def lock(name, limit = 3, **options)
         logger.debug e.backtrace.join("\n")
         raise
       ensure
-        lock_thr.kill
+        lock_thr.kill unless lock_thr.nil?
```
Comment (fmitchell-r7) [inline lib/daemon_runner/semaphore.rb]: Something like this?
```ruby
unless lock_thr.nil?
  lock_thr.kill
  semaphore.release
end
```
That seems like it would be closer to [the original behavior](https://github.com/rapid7/daemon_runner/pull/32/files).

File: lib/daemon_runner/semaphore.rb [hunk 2]
```diff
@@ -19,17 +19,19 @@ def lock(name, limit = 3, **options)
         semaphore = Semaphore.new(options)
         semaphore.lock
         if block_given?
-          lock_thr = semaphore.renew
-          yield
+          begin
+            lock_thr = semaphore.renew
+            yield
+          ensure
+            lock_thr.kill
```
Comment (athompson-r7) [inline lib/daemon_runner/semaphore.rb]: Should we still check for `lock_thr.nil?`

**Comment by athompson-r7** [comment]
Thanks for updating the README 💯

File: lib/daemon_runner/semaphore.rb (hunk 2 above)
Comment (fmitchell-r7) [inline lib/daemon_runner/semaphore.rb]: I don't think [`Thread.new` can return `nil`](https://github.com/rapid7/daemon_runner/blob/0.4.1/lib/daemon_runner/semaphore.rb#L85), so we should be okay.

**Comment by athompson-r7** [comment]
Looks good.  Thanks for fixing this @fmitchell-r7
